<Project>
  <PropertyGroup>
    <!-- Isso avisa o .NET e o Rider que a solução usa CPM -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageVersion Include="MassTransit" Version="8.5.10" />
    <PackageVersion Include="MassTransit.RabbitMQ" Version="8.5.10" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.16.20" />
  </ItemGroup>
</Project>