version: '3.8'

services:
  estoque-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 121415
      POSTGRES_DB: estoquedb
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d estoquedb" ]
      interval: 5s
      timeout: 5s
      retries: 5
  faturamento-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 121415
      POSTGRES_DB: faturamentodb
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d faturamentodb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  estoque-api:
    build:
      context: .
      dockerfile: src/Estoque/Estoque.Api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=estoque-db;Port=5432;Database=estoquedb;Username=postgres;Password=121415;Trust Server Certificate=true;
    depends_on:
      estoque-db:
        condition: service_healthy
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    
  faturamento-api:
    build:
      context: .
      dockerfile: src/Faturamento/Faturamento.Api/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=faturamento-db;Port=5432;Database=faturamentodb;Username=postgres;Password=121415;Trust Server Certificate=true;
    depends_on:
      faturamento-db:
        condition: service_healthy
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
        
  rabbitmq:
    image: rabbitmq:3-management
    container_name: korp_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest