// <auto-generated />
using System;
using Faturamento.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Faturamento.Infrastructure.Migrations
{
    [DbContext(typeof(FaturamentoDbContext))]
    [Migration("20260821192426_InitialFaturamento")]
    partial class InitialFaturamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Faturamento.Domain.Entities.ItemNotaFiscal", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int?>("NotaFiscalId")
                        .HasColumnType("integer")
                        .HasColumnName("nota_fiscal_id");

                    b.Property<int>("Saldo")
                        .HasColumnType("integer")
                        .HasColumnName("saldo");

                    b.HasKey("ItemId")
                        .HasName("pk_item_nota_fiscal");

                    b.HasIndex("NotaFiscalId")
                        .HasDatabaseName("ix_item_nota_fiscal_nota_fiscal_id");

                    b.ToTable("item_nota_fiscal", (string)null);
                });

            modelBuilder.Entity("Faturamento.Domain.Entities.NotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.HasKey("Id")
                        .HasName("pk_nota_fiscal");

                    b.ToTable("nota_fiscal", (string)null);
                });

            modelBuilder.Entity("Faturamento.Domain.Entities.ItemNotaFiscal", b =>
                {
                    b.HasOne("Faturamento.Domain.Entities.NotaFiscal", null)
                        .WithMany("ItemNotaFiscal")
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_item_nota_fiscal_nota_fiscal_nota_fiscal_id");
                });

            modelBuilder.Entity("Faturamento.Domain.Entities.NotaFiscal", b =>
                {
                    b.Navigation("ItemNotaFiscal");
                });
#pragma warning restore 612, 618
        }
    }
}
